controller:
  ingress:
    enabled: true
    paths: []
    apiVersion: "extensions/v1beta1"
    hostName: jenkins.personal.arsalen.xyz
    annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls:
      - secretName: jenkins-tls
        hosts:
          - jenkins.personal.arsalen.xyz