apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec:
  project: default
  sources:
    - repoURL: https://github.com/arsalen021/infra-example.git
      targetRevision: HEAD
      ref: values
      path: argocd
    - repoURL: https://charts.jenkins.io
      targetRevision: 5.7.21
      chart: jenkins
      helm:
        releaseName: jenkins
        valueFiles:
        - $values/argocd/clusters/development/jenkins/values.yaml
  source:
    chart: jenkins
    repoURL: https://charts.jenkins.io
    targetRevision: 5.7.21
  destination:
    name: "in-cluster"
    namespace: jenkins
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true