ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: spring-boot-react-example.personal.arsalen.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: app-tls
      hosts:
        - spring-boot-react-example.personal.arsalen.xyz

livenessProbe: null
readinessProbe: null